name: run the script

on: #whatever you had previously

jobs:
  generate-data:
    runs-on: ${{ matrix.config.os }}
    container: ghcr.io/${{ Github.repository }}:main #put in the correct branch name
    name: ${{ matrix.config.os }} 
    
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest}
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
         token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Script
        run: |
          source("script.R")
        shell: Rscript {0}
      with:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        SSH_PASS: ${{ secrets.SSH_PASS }}
        NGROK_TIMEOUT: 25001
